spring.application.name=messageworker

spring.kafka.consumer.bootstrap-servers=${KAFKA_SERVER}

spring.mongodb.uri=${MONGODB_URI}

products.api.url=${PRODUCTS_API_URL}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=${REDIS_TIMEOUT}